micronaut:
  application:
    name: products
  server:
    cors:
      enabled: true
    port: 8082
---
kafka:
  bootstrap:
    servers: localhost:9092
---
graphql:
  enabled: true
  path: /graphql
  corsEnabled: true
  graphiql:
    enabled: true
    path: /graphiql